### ISSUE TITLE
Cannot successfully create_driver() for using ChromeDriver

### ISSUE THREAD

**Issue by mabryj2** [wolfmanstout/dragonfly-commands#1]
This is possibly a system config issue. Any help much appreciated because I cannot start the ChromeDriver. I tried running the basic command that is first run when starting the driver and got the following traceback.  

```
>>> import json
>>> import urllib2
>>> urllib2.urlopen("http://127.0.0.1:9222/json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\Lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\Lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
```

**Comment by mabryj2** [comment]
Oh, found comment at http://handsfreecoding.org/?p=62 about changing Target for Chrome shortcut.   It would be  nice to have this detail in the README.

**Comment by wolfmanstout** [comment]
Linked instructions in README.
